### ISSUE TITLE
Missing: Language setting for auto generated numbers

### ISSUE THREAD

**Issue by vweimer** [Servoy/svyGCharts#1]
Tool tips generated by the chart component do show the value for a number e.g. 3000 as 3,000. This looks like "en" format, which is default for the language setting for Google Charts.

Would it be possible to make this setting configurable for the developer or taken from the browser language setting? e.g. 3000.33 would be in "en" - 3,000.33 and in "de" 3.000,33.

**Comment by pruhsert** [comment]
Yes, Google Charts uses the "en" locale as default. It can be set, but the problem is it has to be set when the libraries are loaded (as part of the URL). For the component, that is too late (the chart libraries are already loaded or at least the URL is set before the component is initialized). So I do not see how a developer can provide the locale he wants. Anything on the model (a property of the component) comes too late.

What you could do to at least test if it behaves different is to download the source code of the component and inside go to svygooglecharts/js/ng-google-chart.js and there in line 431 you see

packages: ['corechart']

That you could change to

packages: ['corechart'], 'language': 'de'

which should make it German.

Actually, I see only two options to get this right:

1. Have something like a config txt file somewhere on the media of the solution with a specific name that I can load before the component is initialized

That's not so nice because it requires that the name and location is exact...

2. Create a service that you call onSolutionOpen for example

Something like plugins.svyGCharts.loaderSettings: {packages: ['corechart'], language: 'de'}

That feels a bit like an overkill...

**Comment by pruhsert** [comment]
I see one improvement we could implement: simply preset the browser's locale. So if the browser is "de", I could use that to load stuff in "de". I guess that would fit most people, what do you think?

**Comment by vweimer** [comment]
Sounds great to me. This would fit the language the user would expect. At least in most of the cases. (99.99%)

I would go with your suggestion.

Thanks

Best Regards

Mit freundlichen Grüßen
Dipl.-Ing. (FH)
Viktor Weimer
Softwareentwickler/stellvertretender Leiter
Informationsverarbeitung
________________________________

Piepenbrock Service GmbH + Co. KG
Hannoversche Straße 91-95
49084 Osnabrück

Tel.: +49 541 5841-526
Fax: +49 541 5841-869

E-Mail: v.weimer@piepenbrock.de
Web:   www.piepenbrock.de

<http://www.piepenbrock.de/>


<http://www.piepenbrock.de/><https://www.youtube.com/watch?v=bRdHkBBDeTQ><https://www.youtube.com/watch?v=bRdHkBBDeTQ>


________________________________
Kommanditgesellschaft Sitz Osnabrück HRA 6519 AG Osnabrück phG: Piepenbrock Service Verwaltungs- und Beteiligungsgesellschaft mbH HRB 19436 AG Osnabrück Geschäftsführer: Arnulf Piepenbrock, Olaf Piepenbrock, Paul Richter St-Nr.FA:66/204/26100 Osnabrück-Stadt Ust.-ID-Nr.: DE 166472497 Sicherheitsnr Bauabzugssteuer: 236620340108
________________________________

[www.piepenbrock.de]            [www.piepenbrock.de]

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten diese E-Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser E-Mail ist nicht gestattet.
Denken Sie an unsere Umwelt bevor Sie diese E-mail ausdrucken. Please consider the environment before printing this email.

Von: Patrick Ruhsert [mailto:notifications@github.com]
Gesendet: Donnerstag, 16. März 2017 22:28
An: Servoy/svyGCharts
Cc: Weimer, Viktor; Author
Betreff: [*SPAM* (GFI header-Prüfung)] - Re: [Servoy/svyGCharts] Missing: Language setting for auto generated numbers (#1) - E-Mail in Betreffzeile gefunden


I see one improvement we could implement: simply preset the browser's locale. So if the browser is "de", I could use that to load stuff in "de". I guess that would fit most people, what do you think?

**Comment by pruhsert** [comment]
changed in https://github.com/Servoy/svyGCharts/releases/tag/v1.0.1
